import React, { Component } from 'react';
import Cardlist from './Cardlist';
import { phishheadz } from './phishheadz';
import SearchBox from './SearchBox';
import './App.css';
import { Text, Linking } from 'react-native';

class App extends Component {
    constructor() {
        super()
        this.state = {
            phishheadz: phishheadz,
            searchfield: '',
        }
    }

    onSearchChange = (event) => {
        this.setState({ searchfield: event.target.value })
    }

    render() {
        const filteredPhish = this.state.phishheadz.filter(phishhead => {
            return phishhead.name.toLowerCase().includes(this.state.searchfield.toLowerCase())
        })
        return (
            <div>
                <h1 className='tc'>Phish Headz</h1>
                <div className='tc'>
                    <Text style={{ fontFamily: 'monaco' }}
                        onPress={() => Linking.openURL('https://discord.gg/ZWbC5JVtSB')}>
                        Discord{"  "}
                    </Text>
                    <Text style={{ fontFamily: 'monaco' }}
                        onPress={() => Linking.openURL('https://opensea.io/collection/phishheadz')}>
                        {"  "}Opensea{"  "}
                    </Text>
                    <Text style={{ fontFamily: 'monaco' }}
                        onPress={() => Linking.openURL('https://twitter.com/davehead_')}>
                        {"  "}Twitter
                    </Text>
                </div>
                <div class="mw9 center ph3-ns">
                    <div class="cf ph2-ns">
                        <div class="fl w-100 w-25-ns pa3">
                            <div class="pv4">
                                <h5>About</h5>
                                <p id='intro'>
                                    Each Phish Head was algorithmically generated by combining various attributes using 4 categories<br /> (Background, Expression, EQT, and Color).<br /><br />
                                    No Phish are the same.<br /><br />
                                    Once every Phish Head is sold, holders* will be airdropped a new Phish from the Gen 2 collection.
                                </p>
                            </div>
                        </div>
                        <div class="fl w-100 w-25-ns pa3">
                            <div class="pv4">
                                <h5>Distribution</h5>
                                <p id='intro'>
                                    You must hold either of the following at the time the final Phish is sold.<br /><br /> One from Set 1<br />Three from Set 2<br />Four from Set 3<br />Five from Set 4<br />Two from Set 5.
                                </p>
                            </div>
                        </div>
                        <div class="fl w-100 w-25-ns pa3">
                            <div class="pv4">
                                <h5>Roadmap</h5>
                                <p id='intro'>
                                    Q3 2021. Mint all 151 Phish Headz and begin marketing. ✓<br /><br />
                                    Q4 2021. Start the creation of Gen 2 Phish Headz and distribution.<br /><br />
                                    Q1 2022. Phish Headz application R&D<br /><br />
                                </p>
                            </div>
                        </div>
                        <div class="fl w-100 w-25-ns pa3">
                            <div class="pv4">
                                <h5>Supply</h5>
                                <p id='intro'>
                                    Gen 1: 7,200 total<br /><br />
                                    Set 1 (#001-#029): 1 of 1<br />
                                    Set 2 (#030-#060): 60 of 1<br />
                                    Set 3 (#061-#091): 120 of 1<br />
                                    Set 4 (#092-#094): 240 of 1<br />
                                    Set 5 (#095-#151): 15 of 1<br />
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='pa3 tc'>
                    <SearchBox searchChange={this.onSearchChange}/>
                </div>
                <div className='tc'>
                    <Cardlist phishheadz={filteredPhish} />
                </div>
            </div>
        );
    }
}
export default App;